### ISSUE TITLE
Create Contributor access security roll with elevated, non-global admin privileges

### ISSUE THREAD

**Issue by kenoshabrickk** [openoversightva/openoversightva#134]
The Administrator access level is too high to grant to anonymous online contributors. The only role below that one, I think, is the Approved User, who I'm pretty sure can't do too much more than classify images. That's a lot of volunteer help we could really use.

It would be significantly better to allow volunteers to create incidents, add source links, and other information tied to their handle on the site, then it can be removed if there's a problem. Documents should be able to be submitted, then approved before publishing, ideally, but that's less important for right now

There are like 100 pending approval requests **(!)** & I almost just went in & authorized them all as admins, at which point it'll send them emails that they're activated. 
The problem there is that then I'm pretty sure it's possible for admins to revoke other people's access privileges. That's way too big of a risk. If we could get this issue expedited, I'd love to get that queue of pending users cleared out & have them good to go when the approval email hits their inbox.

Edit: I recognize the risk with letting people add links, in hindsight, and a [Captcha  ](https://developers.google.com/recaptcha/intro) would be a good idea/not too complex to implement. As long as contributions are tied to a specific username, I think it'd be pretty straightforward to remove a problem user. Requiring email confirmation alone clears out the risk of most bot-style attacks, but we do still have the issue of humans. I think it's easier to try elevating access privileges for the Approved User and/or Confirmed User roles then roll back anything that's not working. 

@kfinity I know we've discussed this & IIRC agree there's a need

**Comment by kfinity** [comment]
Fixed by #135
