### ISSUE TITLE
update donation linkes

### ISSUE THREAD

**Issue by bryan-va** [openoversightva/openoversightva#61]

**Comment by kenoshabrickk** [comment]
[GoFundMe](https://www.gofundme.com/open-oversight-va-foia-the-police)
[Paypal](https://www.paypal.com/pools/c/8ThAEuPmSy)
[Patreon](https://www.patreon.com/openoversightvirginia)
[OpenCollective](https://opencollective.com/rpd-watch/projects/rpd-cwatch/donate?interval=oneTime&amount=20&name=&legalName=&email=)
